package com.market.adminService;

public class AdminHelper {

	public void help()
	{
		System.out.println("Create store-> To create store\n"
				+ "----------------------------------------\n"
				+ "Create user-> To create user\n"
				+ "----------------------------------------\n"
				+ "Create product-> To create product\n"
				+ "----------------------------------------\n"
				+ "Create admin-> To create admin\n"
				+ "----------------------------------------\n"
				+ "Create unit-> To create store\n"
				+ "----------------------------------------\n"
				+ "Create admin-> To create admin\n"
				+ "----------------------------------------\n"
				+ "Edit store-> To edit store\n"
				+ "----------------------------------------\n"
				+ "Edit admin-> To edit admin\n"
				+ "----------------------------------------\n"
				+ "Edit worker-> To edit user\n"
				+ "----------------------------------------\n"
				+ "Edit product-> To edit shop\n"
				+ "----------------------------------------\n"
				+ "Edit unit-> To edit unit\n"
				+ "----------------------------------------\n"
				+ "Delete store-> To delete the store\n"
				+ "----------------------------------------\n"
				+ "Delete unit-> To delete the unit\n"
				+ "----------------------------------------\n"
				+ "Delete admin-> To delete the admin\n"
				+ "----------------------------------------\n"
				+ "Delete user-> To delete the user\n"
				+ "----------------------------------------\n"
				+ "Delete product-> To delete the product\n"
				+ "----------------------------------------\n"
				+ "Count worker-> To find number of users\n"
				+ "----------------------------------------\n"
				+ "Count product-> To find number of products\n"
				+ "----------------------------------------\n"
				+ "List product-> To listout all the products\n"
				+ "----------------------------------------\n"
				+ "List worker-> To listout all the users\n"
				+ "----------------------------------------\n"
				+ "List worker -p 10--> To listout first ten user\n"
				+ "----------------------------------------\n"
				+ "List product -p 10-> To listout first ten products\n"
				+ "----------------------------------------\n"
				+ "list product product name->To display about the products\n"
				+ "----------------------------------------\n"
				+ "list product catagory->To list products according to catagory\n"
				+ "----------------------------------------\n"
				+ "List worker -p 10 n-> To listout ten users from nth page\n"
				+ "----------------------------------------\n"
				+ "List product -p 10 n--> To listout ten user from nth page\n"
				+ "----------------------------------------\n"
				+ "List records--> To list all shopping records\n"
				+ "----------------------------------------\n"
				+ "List records date--> To list all shopping records for a given date\n"
				+ "----------------------------------------\n"
				+ "Exit-> To exit\n"
				+ "----------------------------------------"
				);
	}
}
